sudo: false
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
before_install:
  - sudo apt-get -qq update
install:
  - pip install -U coverage==4.3
  - pip install codeclimate-test-reporter
script:
  - coverage run --source=. -m unittest discover -v
  - CODECLIMATE_REPO_TOKEN=40cb00907f7a10e04868e856570bb997ab9c42fd3b63d980f2b2269433195fdf codeclimate-test-reporter
addons:
  code_climate:
    repo_token: 40cb00907f7a10e04868e856570bb997ab9c42fd3b63d980f2b2269433195fdf
